-- +goose Up
CREATE TABLE IF NOT EXISTS participants (
    id bigint generated by default as identity primary key,
    name text not null,
    created_at timestamp NOT NULL,
    updated_at timestamp NOT NULL
);

CREATE TABLE IF NOT EXISTS tournament_participants (
    tournament_id bigint NOT NULL REFERENCES tournaments (id) ON DELETE CASCADE,
    participant_id bigint NOT NULL REFERENCES participants (id) ON DELETE CASCADE,
    PRIMARY KEY (tournament_id, participant_id)
);

-- +goose Down
