-- +goose Up
CREATE TABLE outbox (
    id          bigint generated by default as identity PRIMARY KEY,
    topic       TEXT NOT NULL,
    key         TEXT NOT NULL,          -- ключ партиционирования (tournament_id)
    message     JSONB NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    sent_at     TIMESTAMPTZ             -- NULL = не отправлено
);

CREATE INDEX idx_outbox_pending ON outbox (created_at) WHERE sent_at IS NULL;

-- +goose Down
DROP TABLE IF EXISTS outbox;
