-- +goose Up
CREATE TABLE IF NOT EXISTS tournaments (
    id bigint generated by default as identity primary key,
    name text NOT NULL,
    discipline text NOT NULL,
    bracket_format text NOT NULL,
    max_participants int NOT NULL,
    start_date timestamp NOT NULL,
    end_date timestamp NOT NULL,
    created_at timestamp NOT NULL,
    updated_at timestamp NOT NULL
);

-- +goose Down